name: PvpRush
version: 1.0.0
author: WilliamD47
main: net.williamd47.pvprush.Main
description: pvp rush jjrascal epic

commands:
  prush:
    description: /prush [other] to start game with you and [other]
  erush:
    description: /erush ends game