name: PvpRush
version: 1.0.0
author: WilliamD47
main: net.williamd47.pvprush.Main
description: pvp rush jjrascal epic

commands:
  startrush:
    description: /startrush [other] to start game with you and [other]
  endrush:
    description: /endrush ends game